{
 "title": "DMARC Reports",
 "description": "Dashboard for reviewing reports from ParseDMARC",
 "tags": [
  "DKIM",
  "SPF",
  "DMARC",
  "Email"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasourceag", "label": "Datasource: Aggregate", "query": "elasticsearch" },
   { "name": "datasourcefo", "label": "Datasource: Forensic", "query": "elasticsearch" },
   {
    "name": "fromdomain",
    "label": "From Domain",
    "query": "{\"find\":\"terms\",\"field\":\"header_from.keyword\"}"
   },
   { "name": "interval", "label": "Interval", "query": "1d" },
   { "name": "ip_rep", "label": "Datasource: IP Reputation", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Guide",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 1 },
     "options": {
      "content": "# DMARC Summary\r\nAs the name suggests, this dashboard is the best place to start reviewing your aggregate DMARC data.\r\n\r\nAcross the top of the dashboard, three pie charts display the percentage of alignment pass/fail for SPF, DKIM, and DMARC. Clicking on any chart segment will filter for that value.\r\n\r\n***Note***\r\nMessages should not be considered malicious just because they failed to pass DMARC; especially if you have just started collecting data. It may be a legitimate service that needs SPF and DKIM configured correctly.\r\n\r\nStart by filtering the results to only show failed DKIM alignment. While DMARC passes if a message passes SPF or DKIM alignment, only DKIM alignment remains valid when a message is forwarded without changing the from address, which is often caused by a mailbox forwarding rule. This is because DKIM signatures are part of the message headers, whereas SPF relies on SMTP session headers.\r\n\r\nUnderneath the pie charts. you can see graphs of DMARC passage and message disposition over time.\r\n\r\nUnder the graphs you will find the most useful data tables on the dashboard. On the left, there is a list of organizations that are sending you DMARC reports. In the center, there is a list of sending servers grouped by the base domain in their reverse DNS. On the right, there is a list of email from domains, sorted by message volume.\r\n\r\nBy hovering your mouse over a data table value and using the magnifying glass icons, you can filter on or filter out different values. Start by looking at the Message Sources by Reverse DNS table. Find a sender that you recognize, such as an email marketing service, hover over it, and click on the plus (+) magnifying glass icon, to add a filter that only shows results for that sender. Now, look at the Message From Header table to the right. That shows you the domains that a sender is sending as, which might tell you which brand/business is using a particular service. With that information, you can contact them and have them set up DKIM.\r\n\r\n***Note***\r\nIf you have a lot of B2C customers, you may see a high volume of emails as your domains coming from consumer email services, such as Google/Gmail and Yahoo! This occurs when customers have mailbox rules in place that forward emails from an old account to a new account, which is why DKIM authentication is so important, as mentioned earlier. Similar patterns may be observed with businesses who send from reverse DNS addressees of parent, subsidiary, and outdated brands.\r\n\r\n***Note***\r\nYou can add your own custom temporary filters by clicking on Add Filter at the upper right of the page.\r\n\r\n# DMARC Forensic Samples\r\nThe DMARC Forensic Samples section contains information on DMARC forensic reports (also known as failure reports or ruf reports). These reports contain samples of emails that have failed to pass DMARC.\r\n\r\n***Note***\r\nMost recipients do not send forensic/failure/ruf reports at all to avoid privacy leaks. Some recipients (notably Chinese webmail services) will only supply the headers of sample emails. Very few provide the entire email.\r\n\r\n# DMARC Alignment Guide\r\nDMARC ensures that SPF and DKIM authentication mechanisms actually authenticate against the same domain that the end user sees.\r\n\r\nA message passes a DMARC check by passing DKIM or SPF, **as long as the related indicators are also in alignment.**\r\n\r\n|           \t| DKIM                                                                                                                                             \t| SPF                                                                                                            \t|\r\n|-----------\t|--------------------------------------------------------------------------------------------------------------------------------------------------\t|----------------------------------------------------------------------------------------------------------------\t|\r\n| **Passing**   \t| The signature in the DKIM header is validated using a public key that is published as a DNS record of the domain name specified in the signature \t| The mail server's IP address is listed in the SPF record of the domain in the SMTP envelope's mail from header \t|\r\n| **Alignment** \t| The signing domain aligns with the domain in the message's from header                                                                           \t| The domain in the SMTP envelope's mail from header aligns with the domain in the message's from header         \t|\r\n\r\n\r\n# Further Reading\r\n[Demystifying DMARC: A guide to preventing email spoofing](https://seanthegeek.net/459/demystifying-dmarc/amp/)\r\n\r\n[DMARC Manual](https://menainfosec.com/wp-content/uploads/2017/12/DMARC_Service_Manual.pdf)\r\n\r\n[What is “External Destination Verification”?](https://dmarcian.com/what-is-external-destination-verification/)"
     },
     "content": "# DMARC Summary\r\nAs the name suggests, this dashboard is the best place to start reviewing your aggregate DMARC data.\r\n\r\nAcross the top of the dashboard, three pie charts display the percentage of alignment pass/fail for SPF, DKIM, and DMARC. Clicking on any chart segment will filter for that value.\r\n\r\n***Note***\r\nMessages should not be considered malicious just because they failed to pass DMARC; especially if you have just started collecting data. It may be a legitimate service that needs SPF and DKIM configured correctly.\r\n\r\nStart by filtering the results to only show failed DKIM alignment. While DMARC passes if a message passes SPF or DKIM alignment, only DKIM alignment remains valid when a message is forwarded without changing the from address, which is often caused by a mailbox forwarding rule. This is because DKIM signatures are part of the message headers, whereas SPF relies on SMTP session headers.\r\n\r\nUnderneath the pie charts. you can see graphs of DMARC passage and message disposition over time.\r\n\r\nUnder the graphs you will find the most useful data tables on the dashboard. On the left, there is a list of organizations that are sending you DMARC reports. In the center, there is a list of sending servers grouped by the base domain in their reverse DNS. On the right, there is a list of email from domains, sorted by message volume.\r\n\r\nBy hovering your mouse over a data table value and using the magnifying glass icons, you can filter on or filter out different values. Start by looking at the Message Sources by Reverse DNS table. Find a sender that you recognize, such as an email marketing service, hover over it, and click on the plus (+) magnifying glass icon, to add a filter that only shows results for that sender. Now, look at the Message From Header table to the right. That shows you the domains that a sender is sending as, which might tell you which brand/business is using a particular service. With that information, you can contact them and have them set up DKIM.\r\n\r\n***Note***\r\nIf you have a lot of B2C customers, you may see a high volume of emails as your domains coming from consumer email services, such as Google/Gmail and Yahoo! This occurs when customers have mailbox rules in place that forward emails from an old account to a new account, which is why DKIM authentication is so important, as mentioned earlier. Similar patterns may be observed with businesses who send from reverse DNS addressees of parent, subsidiary, and outdated brands.\r\n\r\n***Note***\r\nYou can add your own custom temporary filters by clicking on Add Filter at the upper right of the page.\r\n\r\n# DMARC Forensic Samples\r\nThe DMARC Forensic Samples section contains information on DMARC forensic reports (also known as failure reports or ruf reports). These reports contain samples of emails that have failed to pass DMARC.\r\n\r\n***Note***\r\nMost recipients do not send forensic/failure/ruf reports at all to avoid privacy leaks. Some recipients (notably Chinese webmail services) will only supply the headers of sample emails. Very few provide the entire email.\r\n\r\n# DMARC Alignment Guide\r\nDMARC ensures that SPF and DKIM authentication mechanisms actually authenticate against the same domain that the end user sees.\r\n\r\nA message passes a DMARC check by passing DKIM or SPF, **as long as the related indicators are also in alignment.**\r\n\r\n|           \t| DKIM                                                                                                                                             \t| SPF                                                                                                            \t|\r\n|-----------\t|--------------------------------------------------------------------------------------------------------------------------------------------------\t|----------------------------------------------------------------------------------------------------------------\t|\r\n| **Passing**   \t| The signature in the DKIM header is validated using a public key that is published as a DNS record of the domain name specified in the signature \t| The mail server's IP address is listed in the SPF record of the domain in the SMTP envelope's mail from header \t|\r\n| **Alignment** \t| The signing domain aligns with the domain in the message's from header                                                                           \t| The domain in the SMTP envelope's mail from header aligns with the domain in the message's from header         \t|\r\n\r\n\r\n# Further Reading\r\n[Demystifying DMARC: A guide to preventing email spoofing](https://seanthegeek.net/459/demystifying-dmarc/amp/)\r\n\r\n[DMARC Manual](https://menainfosec.com/wp-content/uploads/2017/12/DMARC_Service_Manual.pdf)\r\n\r\n[What is “External Destination Verification”?](https://dmarcian.com/what-is-external-destination-verification/)"
    }
   ]
  },
  { "title": "DMARC Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "SPF Alignment",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:243",
       "fake": true,
       "field": "spf_aligned",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:244",
       "field": "date_range",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:241",
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DKIM Alignment",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dkim_aligned",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DMARC Passage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:385",
       "fake": true,
       "field": "passed_dmarc",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:386",
       "field": "date_range",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:383",
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "SPF Results Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "spf_results.result.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DKIM Results Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dkim_results.result.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "SPF Alignment Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "spf_aligned",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DKIM Alignment Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dkim_aligned",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DMARC Passage Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "passed_dmarc",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Message Disposition Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "disposition.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      { "field": "date_range", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:430",
       "fake": true,
       "field": "date_range",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:428",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Top 2000 Message Sources by Reverse DNS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:920",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "4",
        "size": "2000"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:918",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Reporting Organisations",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:291",
       "fake": true,
       "field": "org_name.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:98",
       "fake": true,
       "field": "org_extra_contact_info.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:96",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Message Volume by Header From",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:388",
       "fake": true,
       "field": "header_from.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:386",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Map of Message Source Countries",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 53 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "source_country.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:711",
       "fake": true,
       "field": "date_range",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:708",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Message Source Countries",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:524",
       "fake": true,
       "field": "source_country.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:522",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "source_reverse_dns.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "source_ip_address.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:384",
       "fake": true,
       "field": "disposition.keyword",
       "id": "12",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:391",
       "fake": true,
       "field": "spf_aligned",
       "id": "13",
       "settings": {
        "min_doc_count": "1",
        "missing": "false",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:398",
       "fake": true,
       "field": "dkim_aligned",
       "id": "14",
       "settings": {
        "min_doc_count": "1",
        "missing": "false",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:405",
       "fake": true,
       "field": "org_name.keyword",
       "id": "15",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:412",
       "fake": true,
       "field": "spf_results.result.keyword",
       "id": "16",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:622",
       "fake": true,
       "field": "header_from.keyword",
       "id": "17",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "fake": true,
       "field": "dkim_results.result.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "50"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Published Policies (as reported)",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "published_policy.adkim.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "published_policy.aspf.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "published_policy.domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "published_policy.fo.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:384",
       "fake": true,
       "field": "published_policy.p.keyword",
       "id": "12",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:391",
       "fake": true,
       "field": "published_policy.pct",
       "id": "13",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:398",
       "fake": true,
       "field": "published_policy.sp.keyword",
       "id": "14",
       "settings": {
        "min_doc_count": "1",
        "missing": "false",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "IP Abuse Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ipAddress.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "abuseConfidenceScore",
       "id": "1",
       "meta": {
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": true
       },
       "type": "extended_stats"
      }
     ],
     "timeField": "last_updated"
    }
   ]
  },
  {
   "title": "Top 1000 Message Source IP Addresses",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:921",
       "fake": true,
       "field": "source_ip_address.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:922",
       "fake": true,
       "field": "source_reverse_dns.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:923",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:924",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:919",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "SPF Alignment Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "header_from.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "envelope_from.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "spf_results.result.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "spf_aligned",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DKIM Alignment Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "header_from.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "dkim_results.selector.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "dkim_results.domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "dkim_results.result.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:798",
       "fake": true,
       "field": "dkim_aligned",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  { "title": "DMARC Forensic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Forensic Samples",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:340",
       "fake": true,
       "field": "Arrival Date (UTC)",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "$$hashKey": "object:341",
       "fake": true,
       "field": "sample.headers.from.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:342",
       "fake": true,
       "field": "sample.headers.to.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:343",
       "fake": true,
       "field": "sample.headers.reply-to.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:344",
       "fake": true,
       "field": "auth_failure.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:345",
       "fake": true,
       "field": "sample.subject.keyword",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:346",
       "fake": true,
       "field": "delivery_results.keyword",
       "id": "14",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:347",
       "fake": true,
       "field": "authentication_results.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:348",
       "fake": true,
       "field": "sample.headers.received.keyword",
       "id": "13",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:338",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  },
  {
   "title": "Forensic Sample Sources by Country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 118 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:60",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:61",
       "fake": true,
       "field": "arrival_date",
       "id": "7",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:58",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  },
  {
   "title": "DMARC Forensic Sample Source Countries",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 8, "y": 118 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:840",
       "fake": true,
       "field": "source_country.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:838",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  },
  {
   "title": "Top 1000 Forensic Sample Source IP Addresses",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 118 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:653",
       "fake": true,
       "field": "source_ip_address.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:654",
       "fake": true,
       "field": "source_reverse_dns.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:655",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:656",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:651",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  }
 ]
}